#include "radio_stations.h"
#include <algorithm>
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>

namespace muisc::radio {

namespace fs = std::filesystem;

double dial_for_name(const std::string& name) {
    uint32_t h = 5381;
    for (unsigned char c : name) h = h * 33u + c;
    const int steps = 206; // 87.5 .. 108.0 in 0.1 MHz steps
    return 87.5 + static_cast<double>(h % steps) / 10.0;
}

std::vector<Station> default_stations() {
    // NOTE: these URLs are the stations' public stream addresses as far as I
    // know them -- edit stations.txt if one has moved. The two TEST entries
    // are generated by ffmpeg itself and work with no network at all.
    auto mk = [](const char* name, const char* genre, const char* country, const char* codec,
                 int kbps, const char* url, bool fav) {
        Station s;
        s.name = name; s.genre = genre; s.country = country; s.codec_hint = codec;
        s.bitrate_hint = kbps; s.url = url; s.favorite = fav;
        s.dial_mhz = dial_for_name(name);
        return s;
    };
    return {
        mk("Radio Paradise",        "Eclectic Rock",   "US", "AAC", 128, "https://stream.radioparadise.com/aac-128", true),
        mk("SomaFM Groove Salad",   "Ambient / Chill", "US", "MP3", 128, "https://ice1.somafm.com/groovesalad-128-mp3", true),
        mk("SomaFM Indie Pop Rocks","Indie",           "US", "MP3", 128, "https://ice1.somafm.com/indiepop-128-mp3", false),
        mk("Deutschlandfunk",       "Info / Culture",  "DE", "MP3", 128, "https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3", true),
        mk("TEST Stereo Chords",    "Test signal",     "--", "PCM",   0, "lavfi:chords", true),
        mk("TEST Sine 440 Hz",      "Test signal",     "--", "PCM",   0, "lavfi:tone", false),
        mk("TEST Pink Noise",       "Test signal",     "--", "PCM",   0, "lavfi:noise", false),
    };
}

// ---- stream URL comparison -------------------------------------------------------------------------
namespace {
struct UrlParts { std::string base; std::vector<std::string> query; };   // base: no scheme, lower-case host, no trailing "/"

UrlParts split_url(std::string u) {
    UrlParts p;
    const size_t hash = u.find('#');
    if (hash != std::string::npos) u.erase(hash);
    std::string q;
    const size_t qm = u.find('?');
    if (qm != std::string::npos) { q = u.substr(qm + 1); u.erase(qm); }
    const size_t sch = u.find("://");
    if (sch != std::string::npos) u.erase(0, sch + 3);
    const size_t slash = u.find('/');
    const size_t host_end = slash == std::string::npos ? u.size() : slash;
    for (size_t i = 0; i < host_end; ++i) u[i] = static_cast<char>(std::tolower(static_cast<unsigned char>(u[i])));
    while (!u.empty() && u.back() == '/') u.pop_back();
    p.base = u;
    size_t pos = 0;
    while (pos <= q.size() && !q.empty()) {
        size_t amp = q.find('&', pos);
        std::string kv = q.substr(pos, amp == std::string::npos ? std::string::npos : amp - pos);
        std::string key = kv.substr(0, kv.find('='));
        for (auto& c : key) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        const bool noise = key.empty() || key == "aggregator" || key == "ref" || key == "source" || key == "src" || key.rfind("utm_", 0) == 0;
        if (!noise) p.query.push_back(kv);
        if (amp == std::string::npos) break;
        pos = amp + 1;
    }
    std::sort(p.query.begin(), p.query.end());
    return p;
}
} // namespace

bool same_stream_url(const std::string& a, const std::string& b) {
    if (a.empty() || b.empty()) return false;
    const UrlParts pa = split_url(a), pb = split_url(b);
    if (pa.base != pb.base) return false;
    const bool qa = a.find('?') != std::string::npos && a.find('?') + 1 < a.size();
    const bool qb = b.find('?') != std::string::npos && b.find('?') + 1 < b.size();
    if (!qa || !qb) return true;          // one side has no query at all: same mount
    return pa.query == pb.query;          // both have one: what is left after dropping tracking parameters must agree
}

static std::string trim(std::string s) {
    size_t a = s.find_first_not_of(" \t\r\n");
    if (a == std::string::npos) return "";
    size_t b = s.find_last_not_of(" \t\r\n");
    return s.substr(a, b - a + 1);
}

// PATHS-tab overrides (empty = the default layout).
static std::string g_stations_file, g_lists_file, g_presets_file;

static void copy_if_missing(const std::string& from, const std::string& to) {
    if (to.empty() || from.empty() || from == to) return;
    std::error_code ec;
    if (fs::exists(to, ec) || !fs::exists(from, ec)) return;
    if (fs::path(to).has_parent_path()) fs::create_directories(fs::path(to).parent_path(), ec);
    fs::copy_file(from, to, ec);
}

static std::string default_file(const char* name) {
    const char* home = std::getenv("HOME");
    if (!home || !*home) home = std::getenv("USERPROFILE");
    return home && *home ? (fs::path(home) / ".config" / "mousiki" / name).string() : std::string(name);
}

static std::string alias_file_for(const std::string& stations_file) {
    return (fs::path(stations_file).parent_path() / "preset_names.txt").string();
}

std::string preset_names_path() {
    return alias_file_for(g_stations_file.empty() ? default_file("stations.txt") : g_stations_file);
}

bool save_preset_names(const std::vector<Station>& all) {
    const fs::path p = preset_names_path();
    std::error_code ec;
    if (p.has_parent_path()) fs::create_directories(p.parent_path(), ec);
    std::ofstream o(p, std::ios::trunc);
    if (!o) return false;
    o << "# Mousiki radio -- second names for the PRESETS pane: url<TAB>name (edited with SHIFT+C in the stations overlay)\n";
    for (const auto& st : all)
        if (!st.preset_name.empty()) o << st.url << '\t' << st.preset_name << '\n';
    return static_cast<bool>(o);
}

static void apply_preset_names(std::vector<Station>& v) {
    std::ifstream in(preset_names_path());
    if (!in) return;
    std::string line;
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty() || line[0] == '#') continue;
        const size_t tab = line.find('\t');
        if (tab == std::string::npos) continue;
        const std::string url = line.substr(0, tab), name = trim(line.substr(tab + 1));
        for (auto& st : v) if (st.url == url) st.preset_name = name;
    }
}

void set_storage_files(const std::string& stations_file, const std::string& lists_file, const std::string& presets_file) {
    copy_if_missing(preset_names_path(), alias_file_for(stations_file));
    // copy from wherever the file is read from right now (the previous override, else the default place)
    copy_if_missing(g_stations_file.empty() ? default_file("stations.txt") : g_stations_file, stations_file);
    copy_if_missing(g_lists_file.empty() ? default_file("stationlists.txt") : g_lists_file, lists_file);
    copy_if_missing(g_presets_file.empty() ? default_file("presets.txt") : g_presets_file, presets_file);
    g_stations_file = stations_file; g_lists_file = lists_file; g_presets_file = presets_file;
}

static std::vector<Station> parse_file(const fs::path& p) {
    std::vector<Station> out;
    std::ifstream in(p);
    if (!in) return out;
    std::string line;
    while (std::getline(in, line)) {
        line = trim(line);
        if (line.empty() || line[0] == '#') continue;
        // name | genre | country | codec | bitrate | url | [*] | [dial MHz]
        std::vector<std::string> f;
        size_t pos = 0;
        while (true) {
            size_t bar = line.find('|', pos);
            f.push_back(trim(line.substr(pos, bar == std::string::npos ? std::string::npos : bar - pos)));
            if (bar == std::string::npos) break;
            pos = bar + 1;
        }
        if (f.size() < 6 || f[0].empty() || f[5].empty()) continue;
        Station s;
        s.name = f[0]; s.genre = f[1]; s.country = f[2]; s.codec_hint = f[3];
        s.bitrate_hint = std::atoi(f[4].c_str());
        s.url = f[5];
        s.favorite = f.size() > 6 && f[6] == "*";
        s.dial_mhz = (f.size() > 7 && !f[7].empty()) ? std::atof(f[7].c_str()) : dial_for_name(s.name);
        out.push_back(std::move(s));
    }
    return out;
}

std::vector<Station> load_stations(std::string* source_out) {
    std::vector<fs::path> candidates;
    const char* home = std::getenv("HOME");
    if (!home || !*home) home = std::getenv("USERPROFILE");
    if (!g_stations_file.empty()) candidates.push_back(fs::path(g_stations_file));
    if (home && *home) candidates.push_back(fs::path(home) / ".config" / "mousiki" / "stations.txt");
    candidates.push_back(fs::path("stations.txt"));
    for (const auto& c : candidates) {
        std::error_code ec;
        if (!fs::exists(c, ec)) continue;
        auto v = parse_file(c);
        if (!v.empty()) {
            if (source_out) *source_out = c.string();
            apply_preset_names(v);
            return v;
        }
    }
    if (source_out) *source_out = "built-in defaults";
    return default_stations();
}

// ---- saving stations -----------------------------------------------------------------------------
static std::string clean_field(std::string v) {
    for (auto& c : v) if (c == '|' ) c = '/'; else if (static_cast<unsigned char>(c) < 32) c = ' ';
    return trim(v);
}

static std::string station_line(const Station& s) {
    std::string l = clean_field(s.name) + " | " + clean_field(s.genre) + " | " + clean_field(s.country) + " | "
                  + clean_field(s.codec_hint) + " | " + std::to_string(std::max(0, s.bitrate_hint)) + " | " + clean_field(s.url);
    if (s.favorite) l += " | *";
    return l;
}

bool append_station_to_file(const Station& st, const std::vector<Station>& all, std::string* where, std::string* err) {
    std::vector<fs::path> candidates;
    const char* home = std::getenv("HOME");
    if (!home || !*home) home = std::getenv("USERPROFILE");
    if (!g_stations_file.empty()) candidates.push_back(fs::path(g_stations_file));
    if (home && *home) candidates.push_back(fs::path(home) / ".config" / "mousiki" / "stations.txt");
    candidates.push_back(fs::path("stations.txt"));
    // the file load_stations() used: the first candidate that exists and holds at least one station
    for (const auto& c : candidates) {
        std::error_code ec;
        if (!fs::exists(c, ec) || parse_file(c).empty()) continue;
        std::string tail;
        {
            std::ifstream in(c, std::ios::binary | std::ios::ate);
            if (in && in.tellg() > 0) { in.seekg(-1, std::ios::end); char last = 0; in.get(last); if (last != '\n') tail = "\n"; }
        }
        std::ofstream out(c, std::ios::app);
        if (!out) { if (err) *err = "cannot write " + c.string(); return false; }
        out << tail << station_line(st) << "\n";
        if (where) *where = c.string();
        return static_cast<bool>(out);
    }
    // no stations.txt yet: create it from the whole in-memory list (defaults + the new station)
    fs::path target = !g_stations_file.empty() || (home && *home) ? candidates.front() : fs::path("stations.txt");
    std::error_code ec;
    if (target.has_parent_path()) fs::create_directories(target.parent_path(), ec);
    std::ofstream out(target);
    if (!out) { if (err) *err = "cannot write " + target.string(); return false; }
    out << "# Mousiki radio mode -- station list (written by the radio; see radio/stations.txt for the format)\n"
           "# name | genre | country | codec | kbps | url | [*] favorite\n";
    for (const auto& s : all) out << station_line(s) << "\n";
    if (where) *where = target.string();
    return static_cast<bool>(out);
}

int preset_slot_for_key(int key) {
    if (key <= 0 || key > 255) return -1;
    for (int i = 0; i < kPresetCount; ++i) if (kPresetKeys[i] == key) return i;
    return -1;
}

std::string presets_path() {
    if (!g_presets_file.empty()) return g_presets_file;
    const char* home = std::getenv("HOME");
    if (!home || !*home) home = std::getenv("USERPROFILE");
    if (home && *home) return (fs::path(home) / ".config" / "mousiki" / "presets.txt").string();
    return "presets.txt";
}

// Shared by preset and list names: no control characters, [ ] | (file syntax) become ( ) /, trimmed, at most
// `max_chars` characters (UTF-8 lead bytes are counted, a sequence is never cut in half).
static std::string clean_name(const std::string& raw, int max_chars) {
    std::string out;
    for (unsigned char ch : raw) {
        if (ch < 32 || ch == 127) continue;
        if (ch == '[') out += '(';
        else if (ch == ']') out += ')';
        else if (ch == '|') out += '/';
        else out += static_cast<char>(ch);
    }
    out = trim(out);
    int chars = 0;
    for (size_t i = 0; i < out.size(); ++i) {
        if ((static_cast<unsigned char>(out[i]) & 0xC0) != 0x80 && ++chars > max_chars) { out.resize(i); break; }
    }
    return trim(out);
}

std::string clean_preset_name(const std::string& raw) { return clean_name(raw, kPresetNameMax); }
std::string clean_list_name(const std::string& raw) { return clean_name(raw, kListNameMax); }

static std::vector<std::string> split_bar(const std::string& line) {
    std::vector<std::string> f;
    size_t pos = 0;
    while (true) {
        size_t bar = line.find('|', pos);
        f.push_back(trim(line.substr(pos, bar == std::string::npos ? std::string::npos : bar - pos)));
        if (bar == std::string::npos) break;
        pos = bar + 1;
    }
    return f;
}

// ---- station lists -------------------------------------------------------------------------------
std::string station_lists_path() {
    if (!g_lists_file.empty()) return g_lists_file;
    const char* home = std::getenv("HOME");
    if (!home || !*home) home = std::getenv("USERPROFILE");
    if (home && *home) return (fs::path(home) / ".config" / "mousiki" / "stationlists.txt").string();
    return "stationlists.txt";
}

std::vector<StationList> load_station_lists(const std::vector<Station>& stations) {
    std::vector<StationList> lists;
    std::ifstream in(station_lists_path());
    if (!in) return lists;
    std::string line;
    StationList* cur = nullptr;
    while (std::getline(in, line)) {
        line = trim(line);
        if (line.empty() || line[0] == '#') continue;
        if (line.front() == '[' && line.back() == ']') {
            StationList l;
            l.name = clean_list_name(line.substr(1, line.size() - 2));
            if (l.name.empty()) l.name = "List " + std::to_string(lists.size() + 1);
            lists.push_back(std::move(l));
            cur = &lists.back();
            continue;
        }
        if (!cur) continue;   // a station line before any [..] header: nothing to put it in
        const auto f = split_bar(line);   // url | name
        int found = -1;
        for (size_t i = 0; i < stations.size() && found < 0; ++i)
            if (!f[0].empty() && stations[i].url == f[0]) found = static_cast<int>(i);
        if (found < 0 && f.size() > 1)
            for (size_t i = 0; i < stations.size() && found < 0; ++i)
                if (stations[i].name == f[1]) found = static_cast<int>(i);
        if (found >= 0 && std::find(cur->items.begin(), cur->items.end(), found) == cur->items.end()) cur->items.push_back(found);
    }
    return lists;
}

bool save_station_lists(const std::vector<Station>& stations, const std::vector<StationList>& lists) {
    std::error_code ec;
    const fs::path p = station_lists_path();
    if (p.has_parent_path()) fs::create_directories(p.parent_path(), ec);
    std::ofstream o(p, std::ios::trunc);
    if (!o) return false;
    o << "# Mousiki radio station lists -- written by the STATION LISTS menu (Shift+P). [list name] followed by: url | station name\n";
    for (const auto& l : lists) {
        o << "\n[" << l.name << "]\n";
        for (int idx : l.items) {
            if (idx < 0 || idx >= static_cast<int>(stations.size())) continue;
            const Station& s = stations[static_cast<size_t>(idx)];
            o << s.url << " | " << s.name << "\n";
        }
    }
    return static_cast<bool>(o);
}

PresetStore load_presets(const std::vector<Station>& stations) {
    PresetStore store;
    std::error_code ec;
    const fs::path p = presets_path();
    if (fs::exists(p, ec)) {
        // The key letters in the file name the slots. A file written by this version starts with an
        // "@keys <letters>" line saying which letters it used; one without it comes from before the
        // key change and used 1234567890qwertz. Slots are looked up in THAT string, so old presets
        // keep their slots instead of being dropped or shifted.
        std::string file_keys = "1234567890qwertz";
        {
            std::ifstream pre(p);
            std::string l;
            while (std::getline(pre, l)) {
                l = trim(l);
                if (l.rfind("@keys", 0) == 0) { file_keys = trim(l.substr(5)); break; }
            }
        }
        std::ifstream in(p);
        std::string line, active_name;
        PresetBank* cur = nullptr;
        while (std::getline(in, line)) {
            line = trim(line);
            if (line.empty() || line[0] == '#') continue;
            if (line.rfind("@active", 0) == 0) { active_name = trim(line.substr(7)); continue; }
            if (line.rfind("@keys", 0) == 0) continue;
            if (line.front() == '[' && line.back() == ']') {
                PresetBank b;
                b.name = clean_preset_name(line.substr(1, line.size() - 2));
                if (b.name.empty()) b.name = "Preset " + std::to_string(store.banks.size() + 1);
                store.banks.push_back(std::move(b));
                cur = &store.banks.back();
                continue;
            }
            // key | url | name
            const auto f = split_bar(line);
            if (f.size() < 2 || f[0].size() != 1) continue;
            const size_t at = file_keys.find(f[0][0]);
            if (at == std::string::npos || at >= static_cast<size_t>(kPresetCount)) continue;
            const int slot = static_cast<int>(at);
            if (!cur) {   // old file without headers: everything up to the first [..] is "Default"
                PresetBank b; b.name = "Default";
                store.banks.push_back(std::move(b));
                cur = &store.banks.back();
            }
            int found = -1;
            for (size_t i = 0; i < stations.size() && found < 0; ++i)
                if (!f[1].empty() && stations[i].url == f[1]) found = static_cast<int>(i);
            if (found < 0 && f.size() > 2)
                for (size_t i = 0; i < stations.size() && found < 0; ++i)
                    if (stations[i].name == f[2]) found = static_cast<int>(i);
            cur->slots[static_cast<size_t>(slot)] = found;   // a station that has disappeared leaves the slot empty
        }
        if (store.banks.empty()) { PresetBank b; b.name = "Default"; store.banks.push_back(std::move(b)); }
        for (size_t i = 0; i < store.banks.size(); ++i)
            if (!active_name.empty() && store.banks[i].name == active_name) store.active = static_cast<int>(i);
        return store;
    }
    // No presets.txt yet: the "*" stations of stations.txt become the first preset.
    PresetBank b; b.name = "Default";
    int slot = 0;
    for (size_t i = 0; i < stations.size() && slot < kPresetCount; ++i)
        if (stations[i].favorite) b.slots[static_cast<size_t>(slot++)] = static_cast<int>(i);
    store.banks.push_back(std::move(b));
    return store;
}

bool save_presets(const std::vector<Station>& stations, const PresetStore& store) {
    std::error_code ec;
    const fs::path p = presets_path();
    if (p.has_parent_path()) fs::create_directories(p.parent_path(), ec);
    std::ofstream o(p, std::ios::trunc);
    if (!o) return false;
    o << "# Mousiki radio presets -- written by the PRESETS menu (P). [preset name] followed by: key | url | station name\n";
    o << "@keys " << kPresetKeys << "\n";
    if (store.active >= 0 && store.active < static_cast<int>(store.banks.size()))
        o << "@active " << store.banks[static_cast<size_t>(store.active)].name << "\n";
    for (const auto& b : store.banks) {
        o << "\n[" << b.name << "]\n";
        for (int i = 0; i < kPresetCount && i < static_cast<int>(b.slots.size()); ++i) {
            const int idx = b.slots[static_cast<size_t>(i)];
            if (idx < 0 || idx >= static_cast<int>(stations.size())) continue;
            const Station& s = stations[static_cast<size_t>(idx)];
            o << kPresetKeys[i] << " | " << s.url << " | " << s.name << "\n";
        }
    }
    return static_cast<bool>(o);
}

} // namespace muisc::radio
