#include "radio_engine.h"
#include "loudness_meter.h"
#include <algorithm>
#include <atomic>
#include <cctype>
#include <chrono>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <sstream>
#include <thread>
#include <vector>
#include "audio_backend.h"
#include "miniaudio.h"
#include "process_util.h"
#include <cstdio>
#include <ctime>
#include <filesystem>

namespace muisc::radio {

namespace {

constexpr int kRate = 48000;
constexpr int kChannels = 2;
constexpr size_t kRingFrames = static_cast<size_t>(kRate) * 10; // 10 s
constexpr size_t kPrebufferFrames = static_cast<size_t>(kRate) * 3 / 2; // start (or resume) at 1.5 s

using Clock = std::chrono::steady_clock;

long long now_ms() {
    return std::chrono::duration_cast<std::chrono::milliseconds>(Clock::now().time_since_epoch()).count();
}

// ---------------------------------------------------------------------------
// Ring buffer: mutex-protected, interleaved stereo float. A short lock per
// block on the audio thread is the same trade the oscilloscope already makes.
// A "generation" number lets a cancelled (stale) worker discover it has been
// replaced the moment it tries to write, without any other signalling.
// ---------------------------------------------------------------------------
struct Ring {
    std::mutex m;
    std::vector<float> buf = std::vector<float>(kRingFrames * kChannels);
    size_t head = 0;   // frame index of the oldest sample
    size_t count = 0;  // frames stored
    unsigned gen = 0;

    unsigned reset() {
        std::lock_guard<std::mutex> lk(m);
        head = count = 0;
        return ++gen;
    }
    // false = this writer's generation is stale; it must stop.
    bool write(unsigned g, const float* in, size_t frames) {
        std::lock_guard<std::mutex> lk(m);
        if (g != gen) return false;
        if (frames >= kRingFrames) { in += (frames - kRingFrames) * kChannels; frames = kRingFrames; head = count = 0; }
        const size_t room = kRingFrames - count;
        if (frames > room) { // live stream running ahead of the device clock: drop the oldest audio
            const size_t drop = frames - room;
            head = (head + drop) % kRingFrames;
            count -= drop;
        }
        size_t tail = (head + count) % kRingFrames;
        for (size_t i = 0; i < frames; ++i) {
            std::memcpy(&buf[tail * kChannels], in + i * kChannels, sizeof(float) * kChannels);
            if (++tail == kRingFrames) tail = 0;
        }
        count += frames;
        return true;
    }
    size_t read(float* out, size_t frames) {
        std::lock_guard<std::mutex> lk(m);
        const size_t n = std::min(frames, count);
        for (size_t i = 0; i < n; ++i) {
            std::memcpy(out + i * kChannels, &buf[head * kChannels], sizeof(float) * kChannels);
            if (++head == kRingFrames) head = 0;
        }
        count -= n;
        return n;
    }
    size_t fill() {
        std::lock_guard<std::mutex> lk(m);
        return count;
    }
};

// One tune() = one Session. Workers hold it (and the ring) by shared_ptr, so a
// cancelled session can finish winding down after the engine is gone.
struct Session {
    Station station;
    int index = -1;
    std::shared_ptr<Ring> ring;
    unsigned gen = 0;
    std::atomic<bool> cancel{false};
    std::atomic<int> state{static_cast<int>(StreamState::Connecting)}; // Connecting/Reconnecting/Failed or 99 = receiving
    std::atomic<long long> first_audio_ms{0};
    std::atomic<int> reconnects{0};
    std::mutex info_m;
    StreamInfo info;
};
constexpr int kReceiving = 99;

std::string host_of(const std::string& url) {
    size_t a = url.find("://");
    a = (a == std::string::npos) ? 0 : a + 3;
    size_t b = url.find_first_of("/:?", a);
    return url.substr(a, b == std::string::npos ? std::string::npos : b - a);
}

// Offline test signals, generated by ffmpeg's lavfi so the whole pipeline
// (spawn, pipe, ring, device, visualizers) can be exercised with no network.
std::string lavfi_args(const std::string& name) {
    if (name == "tone")
        return "-re -f lavfi -i " + shell_quote("sine=frequency=440:sample_rate=48000");
    if (name == "noise")
        return "-re -f lavfi -i " + shell_quote("anoisesrc=color=pink:amplitude=0.25:sample_rate=48000");
    // "chords": two slowly detuning tones per channel -> a drifting Lissajous figure on the XY scope
    return "-re -f lavfi -i " + shell_quote(
        "aevalsrc=0.30*sin(2*PI*220*t+2*sin(2*PI*0.20*t))+0.20*sin(2*PI*277.18*t)"
        "|0.30*sin(2*PI*329.63*t+2*sin(2*PI*0.13*t))+0.20*sin(2*PI*220*t):s=48000");
}

std::string ffmpeg_cmd(const Station& st) {
    std::string cmd = "ffmpeg -nostdin -v error ";
    if (st.synthetic()) {
        cmd += lavfi_args(st.url.substr(6));
    } else {
        // rw_timeout: give up on a stalled socket after 15 s instead of blocking forever.
        cmd += "-rw_timeout 15000000 -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -i " + shell_quote(st.url);
    }
    cmd += " -vn -f f32le -ac 2 -ar " + std::to_string(kRate) + " -";
    return cmd;
}

// ---- recorder: the worker's decoded frames -> a 16-bit WAV (converted to MP3 when it ends) -------------------------
struct Recorder {
    std::mutex m;
    FILE* f = nullptr;
    std::string wav, mp3, title;
    std::atomic<long long> frames{0};
    std::atomic<bool> active{false};
    std::atomic<int> serial{0};
    std::atomic<int> converting{0};   // conversions still running (the destructor waits for them)
    std::string note;           // guarded by m

    static void put_u32(unsigned char* p, unsigned v) { for (int i = 0; i < 4; ++i) p[i] = static_cast<unsigned char>(v >> (8 * i)); }
    static void put_u16(unsigned char* p, unsigned v) { p[0] = static_cast<unsigned char>(v); p[1] = static_cast<unsigned char>(v >> 8); }

    bool start(const std::string& wav_path, const std::string& mp3_path, const std::string& t, std::string* err) {
        std::lock_guard<std::mutex> lk(m);
        if (f) return false;
        std::error_code ec;
        std::filesystem::create_directories(std::filesystem::path(wav_path).parent_path(), ec);
        f = std::fopen(wav_path.c_str(), "wb");
        if (!f) { if (err) *err = "cannot write " + wav_path; return false; }
        unsigned char h[44] = {'R','I','F','F',0,0,0,0,'W','A','V','E','f','m','t',' ',16,0,0,0,1,0,2,0,0,0,0,0,0,0,0,0,4,0,16,0,'d','a','t','a',0,0,0,0};
        put_u32(h + 24, kRate); put_u32(h + 28, kRate * kChannels * 2);
        std::fwrite(h, 1, sizeof h, f);
        wav = wav_path; mp3 = mp3_path; title = t;
        frames.store(0);
        active.store(true);
        return true;
    }
    void write(const float* in, size_t n) {
        if (!active.load(std::memory_order_relaxed)) return;
        std::lock_guard<std::mutex> lk(m);
        if (!f) return;
        std::vector<short> pcm(n * kChannels);
        for (size_t i = 0; i < pcm.size(); ++i) {
            const float v = std::clamp(in[i], -1.0f, 1.0f);
            pcm[i] = static_cast<short>(v * 32767.0f);
        }
        std::fwrite(pcm.data(), sizeof(short), pcm.size(), f);
        frames.fetch_add(static_cast<long long>(n));
    }
    // Closes the WAV and hands the conversion to a detached thread.
    void stop() {
        std::string w, o, t;
        long long fr;
        {
            std::lock_guard<std::mutex> lk(m);
            if (!f) return;
            active.store(false);
            fr = frames.load();
            const unsigned data = static_cast<unsigned>(fr * kChannels * 2);
            unsigned char b[4];
            std::fseek(f, 4, SEEK_SET); put_u32(b, 36 + data); std::fwrite(b, 1, 4, f);
            std::fseek(f, 40, SEEK_SET); put_u32(b, data); std::fwrite(b, 1, 4, f);
            std::fclose(f); f = nullptr;
            w = wav; o = mp3; t = title;
        }
        converting.fetch_add(1);
        std::thread([this, w, o, t, fr]() {
            std::string result;
            if (fr < kRate / 2) {   // under half a second: nothing worth keeping
                std::error_code ec; std::filesystem::remove(w, ec);
                result = "recording too short, discarded";
            } else {
                std::string cmd = "ffmpeg -nostdin -v error -y -i " + shell_quote(w) + " -c:a libmp3lame -q:a 2 -metadata title=" + shell_quote(t) + " " + shell_quote(o);
                ProcResult r = run_capture(cmd, true);
                std::error_code ec;
                if (r.ok() && std::filesystem::exists(o, ec)) { std::filesystem::remove(w, ec); result = "saved " + o; }
                else result = "mp3 conversion failed, kept " + w;
            }
            { std::lock_guard<std::mutex> lk(m); note = result; }
            serial.fetch_add(1);
            converting.fetch_sub(1);
        }).detach();
    }
};
Recorder g_rec;

// ---- worker: ffmpeg -> ring -----------------------------------------------
void sleep_cancellable(const Session& s, int ms) {
    for (int waited = 0; waited < ms && !s.cancel.load(); waited += 100)
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
}

void worker_main(std::shared_ptr<Session> s) {
    int failures_without_audio = 0;
    int backoff_ms = 1000;
    std::vector<char> pending;
    std::vector<float> frames_buf;
    std::vector<char> rd(32768);

    while (!s->cancel.load()) {
        s->state.store(s->reconnects.load() > 0 ? static_cast<int>(StreamState::Reconnecting)
                                                 : static_cast<int>(StreamState::Connecting));
        auto child = spawn_capture(ffmpeg_cmd(s->station), /*merge_stderr=*/false);
        bool got_audio = false;
        if (child) {
            pending.clear();
            std::ptrdiff_t n;
            while (!s->cancel.load() && (n = child->read(rd.data(), rd.size())) > 0) {
                pending.insert(pending.end(), rd.data(), rd.data() + n);
                const size_t frame_bytes = sizeof(float) * kChannels;
                const size_t whole = pending.size() / frame_bytes;
                if (whole == 0) continue;
                frames_buf.resize(whole * kChannels);
                std::memcpy(frames_buf.data(), pending.data(), whole * frame_bytes);
                pending.erase(pending.begin(), pending.begin() + static_cast<std::ptrdiff_t>(whole * frame_bytes));
                if (!s->ring->write(s->gen, frames_buf.data(), whole)) { s->cancel.store(true); break; }
                g_rec.write(frames_buf.data(), whole);
                if (!got_audio) {
                    got_audio = true;
                    failures_without_audio = 0;
                    backoff_ms = 1000;
                    long long expected = 0;
                    s->first_audio_ms.compare_exchange_strong(expected, now_ms());
                    s->state.store(kReceiving);
                }
            }
            // Leaving scope destroys the ChildProcess: closes the pipe (ffmpeg gets SIGPIPE on
            // its next write and exits) and reaps it.
            child.reset();
        }
        if (s->cancel.load()) break;
        if (!got_audio && ++failures_without_audio >= 5) {
            s->state.store(static_cast<int>(StreamState::Failed));
            return;
        }
        s->reconnects.fetch_add(1);
        s->state.store(static_cast<int>(StreamState::Reconnecting));
        sleep_cancellable(*s, backoff_ms);
        backoff_ms = std::min(backoff_ms * 2, 8000);
    }
}

// ---- probe: ffprobe -> station metadata (ICY name/genre/title, codec, bitrate) ----
std::string value_after(const std::string& line, const std::string& key) {
    if (line.compare(0, key.size(), key) == 0 && line.size() > key.size() && line[key.size()] == '=')
        return line.substr(key.size() + 1);
    return "";
}

std::string upper_codec(std::string c) {
    if (c == "aac" || c == "aac_latm") return "AAC";
    if (c == "mp3" || c == "mp3float") return "MP3";
    if (c == "vorbis") return "Vorbis";
    if (c == "opus") return "Opus";
    if (c == "flac") return "FLAC";
    std::transform(c.begin(), c.end(), c.begin(), [](unsigned char ch) { return static_cast<char>(std::toupper(ch)); });
    return c;
}

void apply_stream_title(StreamInfo& info, const std::string& t) {
    size_t dash = t.find(" - ");
    if (dash != std::string::npos) { info.artist = t.substr(0, dash); info.title = t.substr(dash + 3); }
    else { info.artist.clear(); info.title = t; }
}

void probe_main(std::shared_ptr<Session> s) {
    // Polled, not streamed: ffprobe opens its own short connection to the stream. That is the
    // simplest way to get ICY metadata out of ffmpeg without writing an HTTP client, and it is
    // cheap, but it does show up as one extra (brief) listener on the station every 20 s.
    const std::string cmd = "ffprobe -v error -rw_timeout 10000000 "
        "-show_entries format_tags:stream=codec_name,bit_rate,sample_rate,channels "
        "-of default=noprint_wrappers=1 " + shell_quote(s->station.url);
    while (!s->cancel.load()) {
        ProcResult r = run_capture(cmd, false);
        if (s->cancel.load()) return;
        std::istringstream in(r.out);
        std::string line;
        StreamInfo got;
        std::string stream_title;
        bool any = false;
        while (std::getline(in, line)) {
            while (!line.empty() && (line.back() == '\r' || line.back() == '\n')) line.pop_back();
            std::string v;
            if (!(v = value_after(line, "codec_name")).empty()) { got.codec = upper_codec(v); any = true; }
            else if (!(v = value_after(line, "sample_rate")).empty()) got.sample_rate = std::atoi(v.c_str());
            else if (!(v = value_after(line, "channels")).empty()) got.channels = std::atoi(v.c_str());
            else if (!(v = value_after(line, "bit_rate")).empty()) { int b = std::atoi(v.c_str()); if (b > 0) got.bitrate_kbps = b / 1000; }
            else if (!(v = value_after(line, "TAG:icy-br")).empty()) { int b = std::atoi(v.c_str()); if (b > 0) got.bitrate_kbps = b; }
            else if (!(v = value_after(line, "TAG:icy-name")).empty()) got.station = v;
            else if (!(v = value_after(line, "TAG:icy-genre")).empty()) got.genre = v;
            else if (!(v = value_after(line, "TAG:StreamTitle")).empty()) stream_title = v;
        }
        if (any || !stream_title.empty()) {
            std::lock_guard<std::mutex> lk(s->info_m);
            if (!got.codec.empty()) s->info.codec = got.codec;
            if (got.sample_rate) s->info.sample_rate = got.sample_rate;
            if (got.channels) s->info.channels = got.channels;
            if (got.bitrate_kbps) s->info.bitrate_kbps = got.bitrate_kbps;
            if (!got.station.empty()) s->info.station = got.station;
            if (!got.genre.empty()) s->info.genre = got.genre;
            if (!stream_title.empty()) apply_stream_title(s->info, stream_title);
        }
        sleep_cancellable(*s, 20000);
    }
}

} // namespace

// ===========================================================================
struct RadioEngine::Impl {
    std::shared_ptr<Ring> ring = std::make_shared<Ring>();
    mutable std::mutex session_m;
    std::shared_ptr<Session> session;

    ma_context context{};
    bool context_ready = false;
    ma_device device{};
    bool device_ready = false;
    std::string device_error;

    std::atomic<int> volume{70};
    std::atomic<float> fade{1.0f};     // sleep timer fade-out, multiplies the volume (1 = none)
    std::atomic<bool> muted{false};
    std::atomic<bool> primed{false};
    std::atomic<bool> stereo{true};
    // Tuning noise: a burst of radio static that fades in when a station is tuned and fades out once the new stream plays.
    std::atomic<bool> noise_on{false};        // the ON/OFF option
    std::atomic<bool> noise_hold{false};      // set by tune(): static stays up until the stream plays (or the cap runs out)
    std::atomic<bool> noise_restart{false};   // tune() -> the callback restarts its hold timer
    float noise_env = 0.0f;                   // callback only: current static level 0..1
    long long noise_held = 0;                 // callback only: frames the static has been held
    float pk[7] = {0, 0, 0, 0, 0, 0, 0};      // callback only: pink-noise filter state
    uint32_t noise_rng = 0x9E3779B9u;
    int glitch_left = 0, glitch_len = 1, glitch_type = 0, glitch_hold = 8, next_glitch = 4800;   // callback only
    float held = 0.0f;
    std::atomic<bool> norm_on{true};
    std::atomic<float> norm_target{-16.0f};
    std::atomic<float> norm_boost{9.0f};
    std::atomic<bool> meter_reset{true};       // set by tune / stop / the stereo switch; consumed by the callback
    std::atomic<float> lufs{std::numeric_limits<float>::quiet_NaN()};
    std::atomic<float> norm_gain_db{0.0f};
    LoudnessMeter meter{kRate, 2};             // audio thread only
    float norm_cur = -1.0f;                    // applied normalisation gain (linear), audio thread only
    // Equaliser: the UI thread publishes gains through the atomics, the callback re-configures when the generation changed.
    std::atomic<bool> eq_on{false};
    std::array<std::atomic<float>, kEqBands> eq_gains{};
    std::atomic<unsigned> eq_gen{1};
    Equalizer eq;                              // audio thread only
    unsigned eq_seen_gen = 0;                  // audio thread only

    FftVisualizer fft;
    RadioScope scope;
    std::vector<float> mono;   // scratch for the FFT feed, sized before the device starts

    static void data_callback(ma_device* dev, void* output, const void*, ma_uint32 frame_count) {
        auto* self = static_cast<Impl*>(dev->pUserData);
        float* out = static_cast<float*>(output);
        size_t got = 0;
        const size_t want = frame_count;
        if (!self->primed.load()) {
            if (self->ring->fill() >= kPrebufferFrames) self->primed.store(true);
        }
        if (self->primed.load()) {
            got = self->ring->read(out, want);
            if (got < want) self->primed.store(false); // underrun: output silence, refill to the pre-buffer again
        }
        if (got < want) std::memset(out + got * kChannels, 0, (want - got) * kChannels * sizeof(float));

        // Mono: fold left and right together (before the loudness measurement, so it measures what is heard).
        if (!self->stereo.load(std::memory_order_relaxed)) {
            for (size_t i = 0; i < want; ++i) {
                const float m = 0.5f * (out[i * 2] + out[i * 2 + 1]);
                out[i * 2] = out[i * 2 + 1] = m;
            }
        }
        // Loudness of the stream so far (before volume and normalisation).
        if (self->meter_reset.exchange(false)) {
            self->meter.reset(kRate, 2);
            self->lufs.store(std::numeric_limits<float>::quiet_NaN());
        }
        if (got > 0) {
            self->meter.push(out, got);
            self->lufs.store(static_cast<float>(self->meter.integrated_lufs()), std::memory_order_relaxed);
        }
        // Normalisation target gain, exactly like the player: none until measured; clamp(target - lufs, -30, max boost).
        const float lufs = self->lufs.load(std::memory_order_relaxed);
        float norm_target_lin = 1.0f, norm_db = 0.0f;
        if (self->norm_on.load() && !std::isnan(lufs)) {
            norm_db = std::clamp(self->norm_target.load() - lufs, -30.0f, self->norm_boost.load());
            norm_target_lin = std::pow(10.0f, norm_db / 20.0f);
        }
        self->norm_gain_db.store(norm_db, std::memory_order_relaxed);
        if (self->norm_cur < 0.0f) self->norm_cur = norm_target_lin;
        const float alpha = 1.0f - std::exp(-1.0f / static_cast<float>(kRate));   // ~1 s time constant: no clicks
        const float gain = self->muted.load() ? 0.0f : static_cast<float>(self->volume.load()) / 100.0f * self->fade.load();
        // Equaliser (after the loudness measurement, before volume / normalisation, like the player).
        bool eq_run = false;
        if (self->eq_on.load(std::memory_order_relaxed)) {
            const unsigned gen = self->eq_gen.load(std::memory_order_acquire);
            if (gen != self->eq_seen_gen) {
                EqGains g{};
                for (int b = 0; b < kEqBands; ++b) g[static_cast<size_t>(b)] = self->eq_gains[static_cast<size_t>(b)].load(std::memory_order_relaxed);
                self->eq.configure(g, static_cast<int>(kRate));
                self->eq_seen_gen = gen;
            }
            eq_run = self->eq.active();
        } else if (self->eq_seen_gen != 0) {
            self->eq.reset();
            self->eq_seen_gen = 0;
        }
        auto soft = [](float x) {   // like the player: no hard clipping once the equaliser boosts
            constexpr float kKnee = 0.891f;
            const float a = std::fabs(x);
            if (a <= kKnee) return x;
            const float y = kKnee + (1.0f - kKnee) * std::tanh((a - kKnee) / (1.0f - kKnee));
            return x < 0.0f ? -y : y;
        };
        for (size_t i = 0; i < want; ++i) {
            self->norm_cur += alpha * (norm_target_lin - self->norm_cur);
            if (eq_run) self->eq.process(out[i * 2], out[i * 2 + 1]);
            out[i * 2] *= gain * self->norm_cur;
            out[i * 2 + 1] *= gain * self->norm_cur;
            if (eq_run) { out[i * 2] = soft(out[i * 2]); out[i * 2 + 1] = soft(out[i * 2 + 1]); }
        }

        // Tuning noise: attack ~0.12 s, held until the stream really plays (at least 0.45 s, at most 6 s), release ~0.9 s.
        if (self->noise_on.load(std::memory_order_relaxed) || self->noise_env > 0.0005f) {
            if (self->noise_restart.exchange(false)) self->noise_held = 0;
            const bool want_hold = self->noise_on.load(std::memory_order_relaxed) && self->noise_hold.load(std::memory_order_relaxed);
            if (want_hold) {
                self->noise_held += static_cast<long long>(want);
                const bool playing = got == want && self->primed.load();
                if ((playing && self->noise_held > static_cast<long long>(0.45 * kRate)) || self->noise_held > static_cast<long long>(6.0 * kRate))
                    self->noise_hold.store(false);
            }
            const float vol = self->muted.load() ? 0.0f : static_cast<float>(self->volume.load()) / 100.0f * self->fade.load();
            const float a_att = 1.0f - std::exp(-1.0f / (0.04f * static_cast<float>(kRate)));
            const float a_rel = 1.0f - std::exp(-1.0f / (0.30f * static_cast<float>(kRate)));
            const bool hold_now = self->noise_on.load(std::memory_order_relaxed) && self->noise_hold.load(std::memory_order_relaxed);
            const float tgt = hold_now ? 1.0f : 0.0f;
            auto rnd = [self]() { self->noise_rng = self->noise_rng * 1664525u + 1013904223u; return self->noise_rng >> 8; };   // 24 bit
            auto ms = [](float t) { return static_cast<int>(t * 0.001f * static_cast<float>(kRate)); };
            for (size_t i = 0; i < want; ++i) {
                self->noise_env += (tgt > self->noise_env ? a_att : a_rel) * (tgt - self->noise_env);
                const float w = static_cast<float>(static_cast<int>(rnd()) - (1 << 23)) / static_cast<float>(1 << 23);   // white, -1..1
                float* b = self->pk;                                                                                     // Paul Kellet's pink filter
                b[0] = 0.99886f * b[0] + w * 0.0555179f;  b[1] = 0.99332f * b[1] + w * 0.0750759f;
                b[2] = 0.96900f * b[2] + w * 0.1538520f;  b[3] = 0.86650f * b[3] + w * 0.3104856f;
                b[4] = 0.55000f * b[4] + w * 0.5329522f;  b[5] = -0.7616f * b[5] - w * 0.0168980f;
                const float pink = (b[0] + b[1] + b[2] + b[3] + b[4] + b[5] + b[6] + w * 0.5362f) * 0.11f;
                b[6] = w * 0.115926f;
                // Steady bed: pink noise plus a little white hiss, no movement in it.
                const float bed = pink * 0.40f + w * 0.10f;
                float n = bed;
                // Glitches: every 25-250 ms something short breaks the bed up (2-16 ms).
                if (self->glitch_left > 0) {
                    --self->glitch_left;
                    const int pos = self->glitch_len - self->glitch_left;
                    switch (self->glitch_type) {
                        case 0: n = bed * 0.5f + ((rnd() % 55u) == 0u ? (w < 0 ? -1.0f : 1.0f) * (0.35f + 0.002f * static_cast<float>(rnd() % 300u)) : 0.0f); break;   // crackle: dense pops
                        case 1: if (pos % self->glitch_hold == 0) self->held = bed; n = self->held * 1.6f; break;                                                      // stutter: sample and hold
                        case 2: n = bed * 0.06f; break;                                                                                                                  // dropout
                        default: n = std::round(bed * 5.0f) / 5.0f * 1.8f; break;                                                                                         // digital crunch
                    }
                } else if (--self->next_glitch <= 0) {
                    self->glitch_type = static_cast<int>(rnd() % 4u);
                    self->glitch_len = self->glitch_left = ms(2.0f + static_cast<float>(rnd() % 1400u) * 0.01f);
                    self->glitch_hold = 4 + static_cast<int>(rnd() % 40u);
                    self->next_glitch = ms(25.0f + static_cast<float>(rnd() % 22500u) * 0.01f);
                    self->held = bed;
                }
                n *= self->noise_env * vol;
                out[i * 2] += n; out[i * 2 + 1] += n;
            }
        }

        // Visualizers get exactly what went to the device, like in the music player.
        self->scope.push_frames(out, want);
        size_t done = 0;
        while (done < want) {
            const size_t chunk = std::min(want - done, self->mono.size());
            for (size_t i = 0; i < chunk; ++i)
                self->mono[i] = 0.5f * (out[(done + i) * 2] + out[(done + i) * 2 + 1]);
            self->fft.push_samples(self->mono.data(), chunk, kRate);
            done += chunk;
        }
    }
};

RadioEngine::RadioEngine() : impl_(new Impl) { impl_->mono.assign(8192, 0.0f); }

RadioEngine::~RadioEngine() {
    stop();
    for (int i = 0; i < 1200 && g_rec.converting.load() > 0; ++i) std::this_thread::sleep_for(std::chrono::milliseconds(100));   // let a running MP3 conversion finish
    if (impl_->device_ready) ma_device_uninit(&impl_->device);
    if (impl_->context_ready) ma_context_uninit(&impl_->context);
}

bool RadioEngine::open_device(std::string* err) {
    Impl& d = *impl_;
    ma_context_config cc = ma_context_config_init();
    ma_result r;
    const char* use_null = std::getenv("MOUSIKI_RADIO_NULL");
    if (use_null && *use_null == '1') {
        ma_backend nb[] = { ma_backend_null };
        r = ma_context_init(nb, 1, &cc, &d.context);
    } else {
        r = init_platform_audio_context(d.context) ? MA_SUCCESS : MA_ERROR;
    }
    if (r != MA_SUCCESS) {
        d.device_error = "no audio backend available";
        if (err) *err = d.device_error;
        return false;
    }
    d.context_ready = true;

    ma_device_config cfg = ma_device_config_init(ma_device_type_playback);
    cfg.playback.format = ma_format_f32;
    cfg.playback.channels = kChannels;
    cfg.sampleRate = kRate;
    cfg.dataCallback = &Impl::data_callback;
    cfg.pUserData = &d;
    if (ma_device_init(&d.context, &cfg, &d.device) != MA_SUCCESS) {
        d.device_error = "could not open the audio device";
        if (err) *err = d.device_error;
        return false;
    }
    d.device_ready = true;
    if (ma_device_start(&d.device) != MA_SUCCESS) {
        d.device_error = "could not start the audio device";
        if (err) *err = d.device_error;
        return false;
    }
    return true;
}

void RadioEngine::tune(const Station& st, int index) {
    Impl& d = *impl_;
    auto s = std::make_shared<Session>();
    s->station = st;
    s->index = index;
    s->ring = d.ring;
    s->info.station = st.name;
    s->info.genre = st.genre;
    s->info.country = st.country;
    s->info.codec = st.codec_hint;
    s->info.bitrate_kbps = st.bitrate_hint;
    s->info.host = st.synthetic() ? "ffmpeg lavfi (offline)" : host_of(st.url);
    if (st.synthetic()) { s->info.sample_rate = kRate; s->info.channels = (st.url == "lavfi:tone") ? 1 : 2; }
    {
        std::lock_guard<std::mutex> lk(d.session_m);
        if (d.session) d.session->cancel.store(true);
        s->gen = d.ring->reset();      // from here on, the old worker's writes are refused
        d.session = s;
    }
    d.primed.store(false);
    g_rec.stop();                  // a recording belongs to one station
    if (d.noise_on.load()) { d.noise_hold.store(true); d.noise_restart.store(true); }
    d.meter_reset.store(true);
    d.scope.reset();
    d.fft.reset();
    // Detached on purpose: a worker may sit in a blocking read() on a dead socket for up to the
    // rw_timeout; tuning must never wait for that. Each holds its own shared_ptr to what it needs.
    std::thread(worker_main, s).detach();
    if (!st.synthetic()) std::thread(probe_main, s).detach();
}

void RadioEngine::reconnect() {
    Station st;
    int index;
    {
        std::lock_guard<std::mutex> lk(impl_->session_m);
        if (!impl_->session) return;
        st = impl_->session->station;
        index = impl_->session->index;
    }
    tune(st, index);
}

void RadioEngine::stop() {
    Impl& d = *impl_;
    g_rec.stop();
    std::lock_guard<std::mutex> lk(d.session_m);
    if (d.session) d.session->cancel.store(true);
    d.session.reset();
    d.ring->reset();
    d.primed.store(false);
    d.noise_hold.store(false);
    d.meter_reset.store(true);
}

void RadioEngine::set_tune_noise(bool on) { impl_->noise_on.store(on); if (!on) impl_->noise_hold.store(false); }
void RadioEngine::set_fade(float g) { impl_->fade.store(std::clamp(g, 0.0f, 1.0f)); }
void RadioEngine::set_volume(int pct) { impl_->volume.store(std::clamp(pct, 0, 100)); }
bool RadioEngine::start_recording(const std::string& dir, const std::string& stem, const std::string& title, std::string* err) {
    {
        std::lock_guard<std::mutex> lk(impl_->session_m);
        if (!impl_->session) { if (err) *err = "nothing tuned"; return false; }
    }
    const std::filesystem::path base = std::filesystem::path(dir) / stem;
    return g_rec.start(base.string() + ".wav", base.string() + ".mp3", title, err);
}
void RadioEngine::stop_recording() { g_rec.stop(); }

void RadioEngine::set_muted(bool m) { impl_->muted.store(m); }
void RadioEngine::set_stereo(bool on) {
    if (impl_->stereo.exchange(on) != on) impl_->meter_reset.store(true);   // mono and stereo measure differently
}
void RadioEngine::set_normalization(bool on, float target_lufs, float max_boost_db) {
    impl_->norm_target.store(std::clamp(target_lufs, -40.0f, 0.0f));
    impl_->norm_boost.store(std::clamp(max_boost_db, 0.0f, 24.0f));
    impl_->norm_on.store(on);
}

void RadioEngine::set_equalizer(bool on, const EqGains& gains_db) {
    for (int b = 0; b < kEqBands; ++b)
        impl_->eq_gains[static_cast<size_t>(b)].store(std::clamp(gains_db[static_cast<size_t>(b)], kEqMinDb, kEqMaxDb), std::memory_order_relaxed);
    impl_->eq_gen.fetch_add(1, std::memory_order_release);   // publish AFTER the gains are stored
    impl_->eq_on.store(on);
}

RadioStatus RadioEngine::status() const {
    const Impl& d = *impl_;
    RadioStatus st;
    st.volume = d.volume.load();
    st.muted = d.muted.load();
    st.device_ok = d.device_ready;
    st.device_error = d.device_error;
    st.recording = g_rec.active.load();
    st.recording_sec = static_cast<double>(g_rec.frames.load()) / kRate;
    st.record_serial = g_rec.serial.load();
    if (st.record_serial > 0) { std::lock_guard<std::mutex> lk(g_rec.m); st.record_note = g_rec.note; }
    st.lufs = d.lufs.load();
    st.norm_gain_db = d.norm_gain_db.load();
    std::shared_ptr<Session> s;
    {
        std::lock_guard<std::mutex> lk(d.session_m);
        s = d.session;
    }
    if (!s) return st;
    st.tuned_index = s->index;
    st.tuned_name = s->station.name;
    st.tuned_url = s->station.url;
    st.dial_mhz = s->station.dial_mhz;
    st.reconnects = s->reconnects.load();
    st.buffer_sec = static_cast<double>(d.ring->fill()) / kRate;
    const int raw = s->state.load();
    if (raw == kReceiving) st.state = d.primed.load() ? StreamState::Live : StreamState::Buffering;
    else st.state = static_cast<StreamState>(raw);
    const long long t0 = s->first_audio_ms.load();
    if (t0 > 0) st.listening_sec = static_cast<double>(now_ms() - t0) / 1000.0;
    {
        std::lock_guard<std::mutex> lk(s->info_m);
        st.info = s->info;
    }
    return st;
}

FftVisualizer& RadioEngine::fft() { return impl_->fft; }
RadioScope& RadioEngine::scope() { return impl_->scope; }

} // namespace muisc::radio
